site_name: PRG Toolbox
theme:
  name: material
  palette:
    scheme: violet

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: true
            show_category_heading: true
            group_by_category: true

nav:
  - Home: index.md
  - The coarse graining method: reference_coarse_graining.md
  - Statistical observables: reference_observables.md
  - Analysis tools: reference_analysis_tools.md
  - Plotting library: reference_plotting.md
  - Configuration: reference_config.md
  - Pipelines: reference_pipelines.md